---

- name: Generate ssl certificate
  command: mysql_ssl_rsa_setup
  args:
    creates: /var/lib/mysql/private_key.pem

- name: "set sql certificates in {{ mysql_conf_path[ansible_os_family] }}"
  lineinfile:
    dest="{{ mysql_conf_path[ansible_os_family] }}" 
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^ssl-ca',       line: 'ssl-ca=/var/lib/mysql/ca.pem' }
    - { regexp: '^ssl-cert',     line: 'ssl-cert=/var/lib/mysql/server-cert.pem' }
    - { regexp: '^ssl-key',      line: 'ssl-key=/var/lib/mysql/server-key.pem' }
    - { regexp: '^bind-address', line: 'bind-address=0.0.0.0' }
  notify: restart mysql server

