---

- name: "Update MySQL root password for localhost root account {{ mysql_root_password }}"
  shell: mysql --connect-expired-password -u root -NBe 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  environment:
    MYSQL_PWD: "{{ mysql_root_password }}"

- name: Copy .my.cnf file with root password credentials
  template: src=user-my.cnf.j2 dest=~/.my.cnf mode=0600

- name: Get list of all hosts for the root user.
  shell: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  check_mode: no
  register: mysql_root_hosts

# We must update all root password for all hosts in one shot. Doing it
# separately means we will have to deal with the order issue - the root
# password of user/host pair for doing these update must updated last, or
# updating will fail.
# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account 
  shell: mysql -u root -NBe 'ALTER USER "root"@"{{ item }}" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  with_items: "{{ mysql_root_hosts.stdout_lines | default([]) }}"

## See:
## - http://howtolamp.com/lamp/mysql/5.6/securing/

## These implementations are not good enough:
## - https://github.com/bennojoy/mysql
## - https://github.com/geerlingguy/ansible-role-mysql
## - http://stackoverflow.com/a/16652653

- name: Disallow root login remotely
  command: 'mysql  -u root -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

# ----------------------------------------------------------------------------

- name: Delete anonymous MySQL server user for localhost
# mysql_user: user='' host_all=yes state="absent"
  command: 'mysql -u root --password="{{ mysql_root_password }}" -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User = ''
    - FLUSH PRIVILEGES

# ----------------------------------------------------------------------------

- name: Forbid access to MySQL test database
  command: 'mysql -u root --password="{{ mysql_root_password }}" -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.db WHERE Db LIKE 'test%'
    - FLUSH PRIVILEGES

- name: Remove the MySQL test database
  environment:
    MYSQL_PWD: "{{ temp_password }}"
  mysql_db: db=test state=absent

# ----------------------------------------------------------------------------

# TODO: when os is linux, or there is no /dev/null to link to
- name: Disabling MySQL Server history file
  file: state=link force=yes path=~/.mysql_history src=/dev/null

